-- GENERATED by scripts/generate-seed.ts — do not edit by hand.
-- Loaded on `supabase db reset` (config.toml [db.seed]). Seeds a confirmed auth
-- user and a character owned by them, parsed from lib/btcc/__fixtures__/lisa.btcc.
-- Local/dev convenience only — never run against a real project.

-- 1) Confirmed email/password user. email_confirmed_at => already "approved".
--    The on_auth_user_created trigger auto-creates the matching profiles row.
--    confirmation_token/etc. are set to '' (not NULL) so GoTrue's string scans
--    don't choke; encrypted_password is schema-qualified to be search-path-safe.
insert into auth.users (
  instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
  raw_app_meta_data, raw_user_meta_data, created_at, updated_at,
  confirmation_token, recovery_token, email_change_token_new, email_change
) values (
  '00000000-0000-0000-0000-000000000000',
  '11111111-1111-1111-1111-111111111111',
  'authenticated', 'authenticated',
  'burcinsayin@gmail.com',
  extensions.crypt('an1me4me', extensions.gen_salt('bf')),
  now(),
  '{"provider":"email","providers":["email"]}',
  '{"display_name":"Burcin"}',
  now(), now(),
  '', '', '', ''
)
on conflict do nothing;

-- 2) Email identity (required for password sign-in in GoTrue v2).
insert into auth.identities (
  provider_id, user_id, identity_data, provider, last_sign_in_at, created_at, updated_at
) values (
  '11111111-1111-1111-1111-111111111111',
  '11111111-1111-1111-1111-111111111111',
  '{"sub":"11111111-1111-1111-1111-111111111111","email":"burcinsayin@gmail.com","email_verified":true,"phone_verified":false}',
  'email',
  now(), now(), now()
)
on conflict do nothing;

-- 3) Character owned by the seed user (lisa.btcc). RLS is bypassed here (seed
--    runs as the superuser); columns follow the migration JSONB contract.
insert into public.characters (
  id, owner_id, campaign_id, name, info, attributes, skills, traits, pre_snapshot, notes
) values (
  '22222222-2222-2222-2222-222222222222',
  '11111111-1111-1111-1111-111111111111',
  null,
  $name$Lisa$name$,
  $info${"scalars":{"name":"Lisa","aff":"Federated Suns","subaff":"Crucis March","clancaste":"For Clans Only","earlychild":"Blue Collar","latechild":"Military School","schoolname":"Military Academy","basicschool":"Basic Training","advschool":"MechWarrior","specschool":"","reallife":"Tour Of Duty","phenotype":"Phenotype/Normal Human","nameplanet":"","sex":"Female","age":21,"haircolor":"Red","eyecolor":"Green","height":168,"weight":47,"gmxpmod":-30,"cbillmod":0},"equip":[],"equipLoc":{},"weapons":[],"chrWeapons":[]}$info$::jsonb,
  $attrs${"BOD":250,"CHA":140,"DEX":200,"EDG":110,"INT":135,"RFL":235,"STR":195,"WIL":240}$attrs$::jsonb,
  $skills$[{"name":"Art/Painting","xp":20},{"name":"Career/Pilot","xp":-30},{"name":"Career/Soldier","xp":115},{"name":"Computers","xp":35},{"name":"Gunnery/`Mech","xp":80},{"name":"Interests/Military History","xp":55},{"name":"Interests/Battlemechs","xp":35},{"name":"Interests/FedSuns History","xp":30},{"name":"Language/English","xp":25},{"name":"Language/French","xp":40},{"name":"Leadership","xp":45},{"name":"Martial Arts","xp":110},{"name":"MedTech","xp":60},{"name":"Melee Weapons","xp":20},{"name":"Navigation/Ground","xp":70},{"name":"Perception","xp":50},{"name":"Piloting/`Mech","xp":80},{"name":"Protocol/FedSuns","xp":110},{"name":"Running","xp":30},{"name":"Sensor Operations","xp":55},{"name":"Small Arms","xp":80},{"name":"Strategy","xp":10},{"name":"Swimming","xp":45},{"name":"Tactics/Land","xp":55},{"name":"Technician/Weapons","xp":55}]$skills$::jsonb,
  $traits$[{"name":"Connections","xp":40},{"name":"Equipped","xp":100},{"name":"Fit","xp":15},{"name":"Natural Aptitude/Strategy","xp":100},{"name":"Rank","xp":270},{"name":"Unlucky","xp":-50},{"name":"Vehicle","xp":350}]$traits$::jsonb,
  $pre${"preAttrs":{"DEX":400,"INT":400,"RFL":400,"WIL":300},"preSkills":[],"preTraits":[]}$pre$::jsonb,
  $notes$-----Wizard Data-----
Affilation: Federated Suns
SubAffilation: Crucis March
Cast: For Clans Only
Early Childhood: Blue Collar
Late Childhood: Military School
School: Military Academy
Basic school: Basic Training
Advanced school: MechWarrior
Special school: 
Real Life: Tour Of Duty

Character created by Bearchik from "The Time of War" rules book.$notes$
)
on conflict do nothing;
