// Generates supabase/seed.sql (loaded on `supabase db reset`, see config.toml
// [db.seed]). Seeds one confirmed auth user and a character owned by them whose
// data is parsed from lib/btcc/__fixtures__/lisa.btcc through the same
// parse → column mapping the app uses, so the seed stays byte-faithful to the
// fixture. Re-generate with: npm run seed:generate
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { parseBtcc } from "../lib/btcc";
import { readFixture } from "../lib/btcc/test-fixtures";
import { draftToColumns } from "../lib/characters/mapping";

const SEED_EMAIL = "burcinsayin@gmail.com";
const SEED_PASSWORD = "an1me4me";
const SEED_DISPLAY_NAME = "Burcin";
// Fixed ids so the seed is deterministic across resets.
const USER_ID = "11111111-1111-1111-1111-111111111111";
const CHARACTER_ID = "22222222-2222-2222-2222-222222222222";

const cols = draftToColumns(parseBtcc(readFixture("lisa.btcc")));

// Dollar-quote so JSON/notes need no escaping (the data contains no `$tag$`).
const jq = (tag: string, value: unknown) =>
  `$${tag}$${typeof value === "string" ? value : JSON.stringify(value)}$${tag}$`;

const sql = `-- GENERATED by scripts/generate-seed.ts — do not edit by hand.
-- Loaded on \`supabase db reset\` (config.toml [db.seed]). Seeds a confirmed auth
-- user and a character owned by them, parsed from lib/btcc/__fixtures__/lisa.btcc.
-- Local/dev convenience only — never run against a real project.

-- 1) Confirmed email/password user. email_confirmed_at => already "approved".
--    The on_auth_user_created trigger auto-creates the matching profiles row.
--    confirmation_token/etc. are set to '' (not NULL) so GoTrue's string scans
--    don't choke; encrypted_password is schema-qualified to be search-path-safe.
insert into auth.users (
  instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
  raw_app_meta_data, raw_user_meta_data, created_at, updated_at,
  confirmation_token, recovery_token, email_change_token_new, email_change
) values (
  '00000000-0000-0000-0000-000000000000',
  '${USER_ID}',
  'authenticated', 'authenticated',
  '${SEED_EMAIL}',
  extensions.crypt('${SEED_PASSWORD}', extensions.gen_salt('bf')),
  now(),
  '{"provider":"email","providers":["email"]}',
  '{"display_name":"${SEED_DISPLAY_NAME}"}',
  now(), now(),
  '', '', '', ''
)
on conflict do nothing;

-- 2) Email identity (required for password sign-in in GoTrue v2).
insert into auth.identities (
  provider_id, user_id, identity_data, provider, last_sign_in_at, created_at, updated_at
) values (
  '${USER_ID}',
  '${USER_ID}',
  '{"sub":"${USER_ID}","email":"${SEED_EMAIL}","email_verified":true,"phone_verified":false}',
  'email',
  now(), now(), now()
)
on conflict do nothing;

-- 3) Character owned by the seed user (lisa.btcc). RLS is bypassed here (seed
--    runs as the superuser); columns follow the migration JSONB contract.
insert into public.characters (
  id, owner_id, campaign_id, name, info, attributes, skills, traits, pre_snapshot, notes
) values (
  '${CHARACTER_ID}',
  '${USER_ID}',
  null,
  ${jq("name", cols.name)},
  ${jq("info", cols.info)}::jsonb,
  ${jq("attrs", cols.attributes)}::jsonb,
  ${jq("skills", cols.skills)}::jsonb,
  ${jq("traits", cols.traits)}::jsonb,
  ${jq("pre", cols.pre_snapshot)}::jsonb,
  ${jq("notes", cols.notes)}
)
on conflict do nothing;
`;

const here = dirname(fileURLToPath(import.meta.url));
const out = join(here, "..", "supabase", "seed.sql");
writeFileSync(out, sql);
console.log(`Wrote ${out}`);
